= Value Axis

== Tick-Werte
- bis zu 7 oder 8 Zeichen ≙ z. B. Zahl 123.456 oder Datum 01.01.20

== Offsets
- Nutzung für zu lange Zahlen (zu große Zahlen und/oder Zahlen mit vielen Nachkommastellen)
- Angabe mit vorangestelltem + (oder - im Minusbereich), × oder ÷
- Einheit steht immer im Offset, auch wenn dort keine Zahl steht
- Offset-Bereich hat Hintergrundfarbe/n, andere Bereiche nicht
- abwechselnde Nutzung von zwei Farben: bei Übergängen zu einem anderen Wert des Offsets (z. B. Hintergrundfarbe 1 für 1 Mio, Hintergrundfarbe 2 für 2 Mio, Hintergrundfarbe 1 für 3 Mio, usw.)
- bei Übergängen von keiner Zahl zu einer Zahl im Offset (innerhalb einer Achse) steht im eigentlich leeren Feld + 0 vor der Einheit
- mindestens 5 Pixel Abstand zwischen Übergangslinie und Zeichen im Offset
- Übergangslinie ist durchgezogen und die Zahl 0 fällt weg
- wird kein zugehöriger Wert angezeigt, fällt Offset weg
- wird zugehöriger Wert angezeigt, aber nicht genug Platz für alle Zeichen im Offset -> Fadeout des Offset-Werts bis zu vollständiger Transparenz, dabei fällt erst die Einheit weg

=== Offset-Beispiele
- Offset × 1.000.000 mit Tick-Werten 1, 2, 3, usw. ergibt 1.000.000, 2.000.000, 3.000.000, usw. -> sinnvoll beim Rauszoomen
- Offset ÷ 1.000.000 mit Tick-Werten 1, 2, 3, usw. ergibt 0,000001, 0,000002, 0,000003, usw. -> sinnvoll beim Reinzoomen, Zahlen mit vielen Nachkommastellen
- Offset + 1.000.000 mit Tick-Werten 1, 2, 3, usw. ergibt 1.000.001, 1.000.002, 1.000.003, usw.

== Mehr als eine Y-Achse
- X-Achse geht links bis zum linken Ende des ersten Offsets durch
- Ticks und Werte wandern jeweils auf die rechte Seite der Y-Achse
- Offset-Bereich verbleibt links und rutscht an die Y-Achse heran
- Achsentitel klebt gleichbleibend am Offset
- Y-Achsen, Achsentitel und Ticks nehmen die Farbe der entsprechenden Lines an
- Farbigkeit der Offsets kann ebenso gewählt werden, hierfür werden die Tints (aufgehellte Farben) 0,2 und 0,7 genutzt
- Y-Achsen-Bereich hat außer im Offset-Bereich weißen Hintergrund mit 70 % Opacity, damit Zeichen lesbar bleiben
