= Contains Charting related stuff

== Modules Overview

=== artwork

Contains images and concepts

=== backup

Scripts related to creating backups of the releases

=== data-* (api/client/server)

Data server modules - and REST API model

=== demos

Platform independent code for demos

==== demosfx

JavaFX based demos and runner

==== demosjs

JS based demos and runner

=== doc

Common documentation and stuff related to charting

=== examples

Contains examples of MeisterCharts

=== history-algorithms

Data model and calculations related to history

=== history (platform independent) - for usage with REST

Contains history related classes - including data transfer objects and serializers for REST

=== meistercharts

This project dir contains specific JS implementations for customers.

=== meistercharts-algorithms (platform independent)

This module contains algorithm implementations.
All content within this module is independent from any UI framework.

This code can be compiled to JVM and JavaScript

The src/test/kotlin folder contains tests that run using the JVM

=== meistercharts-canvas (platform independent)

Contains layer implementations and canvas related stuff

=== meistercharts-custom

Custom charts for projects that are usually not reused.

=== meistercharts-marketing

Marketing related documentation and (design) files

=== meistercharts-version-info (platform independent)

Contains an object that can be used to resolve the current version number

=== meisterchartsfx

JavaFX specific implementation for the canvas
