@file:Suppress("unused", "SpellCheckingInspection")
package it.neckar.docker

import it.neckar.projects.common.docker.DockerImageDescriptor

/**
 * Auto-generated by [it.neckar.gradle.docker.DockerGenerateObjectsTask]
 */
object ExternalDockerImages {
  val DockerIoAmir20Dozzle: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoAmir20Dozzle.withTag( ExternalDockerImageTags.DockerIoAmir20Dozzle )
  val DockerIoGrafanaGrafanaOss: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoGrafanaGrafanaOss.withTag( ExternalDockerImageTags.DockerIoGrafanaGrafanaOss )
  val DockerIoGrafanaLoki: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoGrafanaLoki.withTag( ExternalDockerImageTags.DockerIoGrafanaLoki )
  val DockerIoJitsiJicofo: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoJitsiJicofo.withTag( ExternalDockerImageTags.DockerIoJitsiJicofo )
  val DockerIoJitsiJvb: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoJitsiJvb.withTag( ExternalDockerImageTags.DockerIoJitsiJvb )
  val DockerIoJitsiProsody: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoJitsiProsody.withTag( ExternalDockerImageTags.DockerIoJitsiProsody )
  val DockerIoJitsiWeb: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoJitsiWeb.withTag( ExternalDockerImageTags.DockerIoJitsiWeb )
  val DockerIoMinioMinio: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoMinioMinio.withTag( ExternalDockerImageTags.DockerIoMinioMinio )
  val DockerIoMongo: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoMongo.withTag( ExternalDockerImageTags.DockerIoMongo )
  val DockerIoMysql: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoMysql.withTag( ExternalDockerImageTags.DockerIoMysql )
  val DockerIoNginx: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoNginx.withTag( ExternalDockerImageTags.DockerIoNginx )
  val DockerIoNickfedorWatchtower: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoNickfedorWatchtower.withTag( ExternalDockerImageTags.DockerIoNickfedorWatchtower )
  val DockerIoPortainerPortainerCe: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoPortainerPortainerCe.withTag( ExternalDockerImageTags.DockerIoPortainerPortainerCe )
  val DockerIoPostgres: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoPostgres.withTag( ExternalDockerImageTags.DockerIoPostgres )
  val DockerIoPromAlertmanager: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoPromAlertmanager.withTag( ExternalDockerImageTags.DockerIoPromAlertmanager )
  val DockerIoPromPrometheus: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoPromPrometheus.withTag( ExternalDockerImageTags.DockerIoPromPrometheus )
  val DockerIoPromPushgateway: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoPromPushgateway.withTag( ExternalDockerImageTags.DockerIoPromPushgateway )
  val DockerIoRcloneRclone: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoRcloneRclone.withTag( ExternalDockerImageTags.DockerIoRcloneRclone )
  val DockerIoSeleniumStandaloneChrome: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoSeleniumStandaloneChrome.withTag( ExternalDockerImageTags.DockerIoSeleniumStandaloneChrome )
  val DockerIoTraefik: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoTraefik.withTag( ExternalDockerImageTags.DockerIoTraefik )
  val DockerIoTwinproductionGatus: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoTwinproductionGatus.withTag( ExternalDockerImageTags.DockerIoTwinproductionGatus )
  val DockerIoVaultwardenServer: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoVaultwardenServer.withTag( ExternalDockerImageTags.DockerIoVaultwardenServer )
  val DockerIoWordpress: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.DockerIoWordpress.withTag( ExternalDockerImageTags.DockerIoWordpress )
  val GhcrIoUmamiSoftwareUmami: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.GhcrIoUmamiSoftwareUmami.withTag( ExternalDockerImageTags.GhcrIoUmamiSoftwareUmami )
  val QuayIoKeycloakKeycloak: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.QuayIoKeycloakKeycloak.withTag( ExternalDockerImageTags.QuayIoKeycloakKeycloak )
  val QuayIoPrometheusNodeExporter: DockerImageDescriptor =  ExternalDockerImagesWithoutTag.QuayIoPrometheusNodeExporter.withTag( ExternalDockerImageTags.QuayIoPrometheusNodeExporter )

  /**
   * Contains all entries within the files
   */
  val entries: List<DockerImageDescriptor> = listOf(
    DockerIoAmir20Dozzle,
    DockerIoGrafanaGrafanaOss,
    DockerIoGrafanaLoki,
    DockerIoJitsiJicofo,
    DockerIoJitsiJvb,
    DockerIoJitsiProsody,
    DockerIoJitsiWeb,
    DockerIoMinioMinio,
    DockerIoMongo,
    DockerIoMysql,
    DockerIoNginx,
    DockerIoNickfedorWatchtower,
    DockerIoPortainerPortainerCe,
    DockerIoPostgres,
    DockerIoPromAlertmanager,
    DockerIoPromPrometheus,
    DockerIoPromPushgateway,
    DockerIoRcloneRclone,
    DockerIoSeleniumStandaloneChrome,
    DockerIoTraefik,
    DockerIoTwinproductionGatus,
    DockerIoVaultwardenServer,
    DockerIoWordpress,
    GhcrIoUmamiSoftwareUmami,
    QuayIoKeycloakKeycloak,
    QuayIoPrometheusNodeExporter,
  )
}
