/*
 * Copyright (C) 2013-2026 Neckar IT GmbH, Mössingen, Germany
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Linking this library statically or dynamically with other modules is
 * making a combined work based on this library. Thus, the terms and
 * conditions of the GNU General Public License cover the whole combination.
 *
 * As a special exception, the copyright holders of this library give you
 * permission to link this library with independent modules, regardless of
 * the license terms of these independent modules, and to copy and distribute
 * the resulting combined work under terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of the source
 * code of this library.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package it.neckar.open.collections

typealias Stack<TGen> = TGenStack<TGen>

// AUTOGENERATED: DO NOT MODIFY MANUALLY!


/**
 * A LIFO (Last In First Out) structure.
 */
class TGenStack<TGen>() : Collection<TGen> {
  private val items = arrayListOf<TGen>()

  override val size: Int get() = items.size
  override fun isEmpty() = size == 0

  constructor(vararg items: TGen) : this() {
    for (item in items) push(item)
  }

  fun push(v: TGen) {
    items.add(v)
  }

  fun pop(): TGen = items.removeAt(items.size - 1)
  fun peek(): TGen? = items.lastOrNull()

  override fun contains(element: TGen): Boolean = items.contains(element)
  override fun containsAll(elements: Collection<TGen>): Boolean = items.containsAll(elements)
  override fun iterator(): Iterator<TGen> = items.iterator()

  override fun hashCode(): Int = items.hashCode()
  override fun equals(other: Any?): Boolean = (other is TGenStack<*/*TGen*/>) && items == other.items
}


// Int

/**
 * A LIFO (Last In First Out) structure.
 */
class IntStack() : Collection<Int> {
  private val items = intArrayListOf()

  override val size: Int get() = items.size
  override fun isEmpty() = size == 0

  constructor(vararg items: Int) : this() {
    for (item in items) push(item)
  }

  fun push(v: Int) = run { items.add(v) }
  fun pop(): Int = items.removeAt(items.size - 1)
  fun peek(): Int? = items.lastOrNull()

  override fun contains(element: Int): Boolean = items.contains(element)
  override fun containsAll(elements: Collection<Int>): Boolean = items.containsAll(elements)
  override fun iterator(): Iterator<Int> = items.iterator()

  override fun hashCode(): Int = items.hashCode()
  override fun equals(other: Any?): Boolean = (other is IntStack) && items == other.items
}


// Double

/**
 * A LIFO (Last In First Out) structure.
 */
class DoubleStack() : Collection<Double> {
  private val items = doubleArrayListOf()

  override val size: Int get() = items.size
  override fun isEmpty() = size == 0

  constructor(vararg items: Double) : this() {
    for (item in items) push(item)
  }

  fun push(v: Double) = run { items.add(v) }
  fun pop(): Double = items.removeAt(items.size - 1)
  fun peek(): Double? = items.lastOrNull()

  override fun contains(element: Double): Boolean = items.contains(element)
  override fun containsAll(elements: Collection<Double>): Boolean = items.containsAll(elements)
  override fun iterator(): Iterator<Double> = items.iterator()

  override fun hashCode(): Int = items.hashCode()
  override fun equals(other: Any?): Boolean = (other is DoubleStack) && items == other.items
}


// Float

/**
 * A LIFO (Last In First Out) structure.
 */
class FloatStack() : Collection<Float> {
  private val items = floatArrayListOf()

  override val size: Int get() = items.size
  override fun isEmpty() = size == 0

  constructor(vararg items: Float) : this() {
    for (item in items) push(item)
  }

  fun push(v: Float) = run { items.add(v) }
  fun pop(): Float = items.removeAt(items.size - 1)
  fun peek(): Float? = items.lastOrNull()

  override fun contains(element: Float): Boolean = items.contains(element)
  override fun containsAll(elements: Collection<Float>): Boolean = items.containsAll(elements)
  override fun iterator(): Iterator<Float> = items.iterator()

  override fun hashCode(): Int = items.hashCode()
  override fun equals(other: Any?): Boolean = (other is FloatStack) && items == other.items
}
