= MeisterCharts Examples

This project contains examples demonstrating how to use the MeisterCharts
JavaScript library with different frameworks such as Yarn, NPM, Vite, and more. Each example showcases a specific integration with a particular framework, providing you with practical usage scenarios and guidance.

== Examples

The "meistercharts-examples" folder contains following examples:

=== Meistercharts minimal

Minimal MeisterCharts examples using a **timeLineChart** to demonstrate the usage of MeisterCharts

- link:./fiddles[fiddles]: JSFiddle example sources
- link:./meistercharts-minimal[meistercharts-minimal]: example using blank HTML, CSS and Javascript.
- link:./npm-meistercharts-minimal[npm-meistercharts-minimal]: example using the npm package manager and webpack bundler
- link:./yarn-meistercharts-minimal[yarn-meistercharts-minimal]: example using the yarn package manager and webpack bundler
- link:./vite-meistercharts-minimal[vite-meistercharts-minimal]: example using vite.js

=== JSFiddle Examples

https://jsfiddle.net/gh/get/library/pure/Neckar-IT/meistercharts/tree/main/meistercharts-examples/fiddles/meistercharts-minimal

