import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val aopalliance: String = "aopalliance:aopalliance:_"

    public const val ca_cutterslade_analyze_gradle_plugin: String =
            "ca.cutterslade.analyze:ca.cutterslade.analyze.gradle.plugin:_"

    public const val logback_classic: String = "ch.qos.logback:logback-classic:_"

    public const val commonmark: String = "com.atlassian.commonmark:commonmark:_"

    public const val commonmark_ext_gfm_tables: String =
            "com.atlassian.commonmark:commonmark-ext-gfm-tables:_"

    public const val uuid: String = "com.benasher44:uuid:_"

    public const val filepeek: String = "com.christophsturm:filepeek:_"

    public const val com_cosminpolifronie_gradle_plantuml_gradle_plugin: String =
            "com.cosminpolifronie.gradle.plantuml:com.cosminpolifronie.gradle.plantuml.gradle.plugin:_"

    public const val com_dorongold_task_tree_gradle_plugin: String =
            "com.dorongold.task-tree:com.dorongold.task-tree.gradle.plugin:_"

    public const val jackson_databind: String = "com.fasterxml.jackson.core:jackson-databind:_"

    public const val jackson_datatype_guava: String =
            "com.fasterxml.jackson.datatype:jackson-datatype-guava:_"

    public const val jackson_datatype_jdk8: String =
            "com.fasterxml.jackson.datatype:jackson-datatype-jdk8:_"

    public const val jackson_datatype_jsr310: String =
            "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:_"

    public const val jackson_module_kotlin: String =
            "com.fasterxml.jackson.module:jackson-module-kotlin:_"

    public const val jackson_module_parameter_names: String =
            "com.fasterxml.jackson.module:jackson-module-parameter-names:_"

    public const val rxjava2_extras: String = "com.github.davidmoten:rxjava2-extras:_"

    public const val kotlin_csv: String = "com.github.doyaaaaaken:kotlin-csv:_"

    public const val kotlin_csv_js: String = "com.github.doyaaaaaken:kotlin-csv-js:_"

    public const val kotlin_csv_jvm: String = "com.github.doyaaaaaken:kotlin-csv-jvm:_"

    public const val com_github_hierynomus_license_base_gradle_plugin: String =
            "com.github.hierynomus.license-base:com.github.hierynomus.license-base.gradle.plugin:_"

    public const val com_github_hierynomus_license_gradle_plugin: String =
            "com.github.hierynomus.license:com.github.hierynomus.license.gradle.plugin:_"

    public const val com_github_johnrengelman_shadow_gradle_plugin: String =
            "com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:_"

    public const val com_github_node_gradle_node_gradle_plugin: String =
            "com.github.node-gradle.node:com.github.node-gradle.node.gradle.plugin:_"

    public const val image_comparison: String = "com.github.romankh3:image-comparison:_"

    public const val rxkotlinfx: String = "com.github.thomasnield:rxkotlinfx:_"

    public const val com_github_turansky_kfc_latest_webpack_gradle_plugin: String =
            "com.github.turansky.kfc.latest-webpack:com.github.turansky.kfc.latest-webpack.gradle.plugin:_"

    public const val curvesapi: String = "com.github.virtuald:curvesapi:_"

    public const val com_google_cloud_tools_jib_gradle_plugin: String =
            "com.google.cloud.tools.jib:com.google.cloud.tools.jib.gradle.plugin:_"

    public const val jsr305: String = "com.google.code.findbugs:jsr305:_"

    public const val guava: String = "com.google.guava:guava:_"

    public const val guice_multibindings: String =
            "com.google.inject.extensions:guice-multibindings:_"

    public const val guice: String = "com.google.inject:guice:_"

    public const val annotations: String = "com.intellij:annotations:_"

    public const val com_javagen_schema_gen_gradle_plugin: String =
            "com.javagen.schema-gen:com.javagen.schema-gen.gradle.plugin:_"

    public const val jfoenix: String = "com.jfoenix:jfoenix:_"

    public const val playwright: String = "com.microsoft.playwright:playwright:_"

    public const val miglayout_javafx: String = "com.miglayout:miglayout-javafx:_"

    public const val miglayout_swing: String = "com.miglayout:miglayout-swing:_"

    public const val klock: String = "com.soywiz.korlibs.klock:klock:_"

    public const val okhttp: String = "com.squareup.okhttp3:okhttp:_"

    public const val javax_mail: String = "com.sun.mail:javax.mail:_"

    public const val assertk: String = "com.willowtreeapps.assertk:assertk:_"

    public const val assertk_js: String = "com.willowtreeapps.assertk:assertk-js:_"

    public const val assertk_jvm: String = "com.willowtreeapps.assertk:assertk-jvm:_"

    public const val commons_cli: String = "commons-cli:commons-cli:_"

    public const val commons_codec: String = "commons-codec:commons-codec:_"

    public const val commons_io: String = "commons-io:commons-io:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val fontawesomefx: String = "de.jensd:fontawesomefx:_"

    public const val de_undercouch_download_gradle_plugin: String =
            "de.undercouch.download:de.undercouch.download.gradle.plugin:_"

    public const val edu_sc_seis_launch4j_gradle_plugin: String =
            "edu.sc.seis.launch4j:edu.sc.seis.launch4j.gradle.plugin:_"

    public const val tilesfx: String = "eu.hansolo:tilesfx:_"

    public const val vworkflows_fx: String = "eu.mihosoft.vrl.workflow:vworkflows-fx:_"

    public const val io_codearte_nexus_staging_gradle_plugin: String =
            "io.codearte.nexus-staging:io.codearte.nexus-staging.gradle.plugin:_"

    public const val kohttp: String = "io.github.rybalkinsd:kohttp:_"

    public const val io_gitlab_arturbosch_detekt_gradle_plugin: String =
            "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:_"

    public const val ktor_client_auth: String = "io.ktor:ktor-client-auth:_"

    public const val ktor_client_cio: String = "io.ktor:ktor-client-cio:_"

    public const val ktor_client_content_negotiation: String =
            "io.ktor:ktor-client-content-negotiation:_"

    public const val ktor_client_core: String = "io.ktor:ktor-client-core:_"

    public const val ktor_client_json: String = "io.ktor:ktor-client-json:_"

    public const val ktor_client_logging: String = "io.ktor:ktor-client-logging:_"

    public const val ktor_client_serialization: String = "io.ktor:ktor-client-serialization:_"

    public const val ktor_client_websockets: String = "io.ktor:ktor-client-websockets:_"

    public const val ktor_http: String = "io.ktor:ktor-http:_"

    public const val ktor_serialization_kotlinx: String = "io.ktor:ktor-serialization-kotlinx:_"

    public const val ktor_serialization_kotlinx_json: String =
            "io.ktor:ktor-serialization-kotlinx-json:_"

    public const val ktor_server: String = "io.ktor:ktor-server:_"

    public const val ktor_server_auth: String = "io.ktor:ktor-server-auth:_"

    public const val ktor_server_auth_jwt: String = "io.ktor:ktor-server-auth-jwt:_"

    public const val ktor_server_core: String = "io.ktor:ktor-server-core:_"

    public const val ktor_server_locations: String = "io.ktor:ktor-server-locations:_"

    public const val ktor_server_metrics: String = "io.ktor:ktor-server-metrics:_"

    public const val ktor_server_netty: String = "io.ktor:ktor-server-netty:_"

    public const val ktor_server_test_host: String = "io.ktor:ktor-server-test-host:_"

    public const val ktor_server_websockets: String = "io.ktor:ktor-server-websockets:_"

    public const val mockk: String = "io.mockk:mockk:_"

    public const val measured: String = "io.nacular.measured:measured:_"

    public const val rxjava: String = "io.reactivex.rxjava2:rxjava:_"

    public const val rxkotlin: String = "io.reactivex.rxjava2:rxkotlin:_"

    public const val io_spring_dependency_management_gradle_plugin: String =
            "io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:_"

    public const val javax_annotation_api: String = "javax.annotation:javax.annotation-api:_"

    public const val javax_inject: String = "javax.inject:javax.inject:_"

    public const val javax_mail_api: String = "javax.mail:javax.mail-api:_"

    public const val mail: String = "javax.mail:mail:_"

    public const val joda_time: String = "joda-time:joda-time:_"

    public const val mattermost_models: String = "net.bis5.mattermost4j:mattermost-models:_"

    public const val mattermost4j_core: String = "net.bis5.mattermost4j:mattermost4j-core:_"

    public const val balloontip: String = "net.java.balloontip:balloontip:_"

    public const val glazedlists_java16: String = "net.java.dev.glazedlists:glazedlists_java16:_"

    public const val launch4j: String = "net.sf.launch4j:launch4j:_"

    public const val svg2ico: String = "net.sourceforge.svg2ico:svg2ico:_"

    public const val tornadofx: String = "no.tornado:tornadofx:_"

    public const val tornadofx_controls: String = "no.tornado:tornadofx-controls:_"

    public const val tornadofx_controlsfx: String = "no.tornado:tornadofx-controlsfx:_"

    public const val commons_compress: String = "org.apache.commons:commons-compress:_"

    public const val commons_lang3: String = "org.apache.commons:commons-lang3:_"

    public const val commons_math3: String = "org.apache.commons:commons-math3:_"

    public const val pdfbox: String = "org.apache.pdfbox:pdfbox:_"

    public const val batik_svggen: String = "org.apache.xmlgraphics:batik-svggen:_"

    public const val batik_svgrasterizer: String = "org.apache.xmlgraphics:batik-svgrasterizer:_"

    public const val batik_swing: String = "org.apache.xmlgraphics:batik-swing:_"

    public const val batik_transcoder: String = "org.apache.xmlgraphics:batik-transcoder:_"

    public const val org_asciidoctor_jvm_convert_gradle_plugin: String =
            "org.asciidoctor.jvm.convert:org.asciidoctor.jvm.convert.gradle.plugin:_"

    public const val org_asciidoctor_jvm_pdf_gradle_plugin: String =
            "org.asciidoctor.jvm.pdf:org.asciidoctor.jvm.pdf.gradle.plugin:_"

    public const val assertj_core: String = "org.assertj:assertj-core:_"

    public const val assertj_guava: String = "org.assertj:assertj-guava:_"

    public const val awaitility: String = "org.awaitility:awaitility:_"

    public const val bcprov_jdk15to18: String = "org.bouncycastle:bcprov-jdk15to18:_"

    public const val staxmate: String = "org.codehaus.staxmate:staxmate:_"

    public const val woodstox_core_asl: String = "org.codehaus.woodstox:woodstox-core-asl:_"

    public const val controlsfx: String = "org.controlsfx:controlsfx:_"

    public const val fest_reflect: String = "org.easytesting:fest-reflect:_"

    public const val freemarker: String = "org.freemarker:freemarker:_"

    public const val fxyz3d: String = "org.fxyz3d:fxyz3d:_"

    public const val chrome_devtools_kotlin: String = "org.hildan.chrome:chrome-devtools-kotlin:_"

    public const val im4java: String = "org.im4java:im4java:_"

    public const val all_modules_page_plugin: String =
            "org.jetbrains.dokka:all-modules-page-plugin:_"

    public const val dokka_analysis: String = "org.jetbrains.dokka:dokka-analysis:_"

    public const val dokka_base: String = "org.jetbrains.dokka:dokka-base:_"

    public const val gfm_template_processing_plugin: String =
            "org.jetbrains.dokka:gfm-template-processing-plugin:_"

    public const val jekyll_template_processing_plugin: String =
            "org.jetbrains.dokka:jekyll-template-processing-plugin:_"

    public const val org_jetbrains_dokka_gradle_plugin: String =
            "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:_"

    public const val intellij_coverage_agent: String =
            "org.jetbrains.intellij.deps:intellij-coverage-agent:_"

    public const val intellij_coverage_reporter: String =
            "org.jetbrains.intellij.deps:intellij-coverage-reporter:_"

    public const val org_jetbrains_intellij_gradle_plugin: String =
            "org.jetbrains.intellij:org.jetbrains.intellij.gradle.plugin:_"

    public const val kotlin_css: String = "org.jetbrains.kotlin-wrappers:kotlin-css"

    public const val kotlin_js: String = "org.jetbrains.kotlin-wrappers:kotlin-js:_"

    public const val kotlin_react: String = "org.jetbrains.kotlin-wrappers:kotlin-react"

    public const val kotlin_react_dom: String = "org.jetbrains.kotlin-wrappers:kotlin-react-dom"

    public const val kotlin_react_redux: String = "org.jetbrains.kotlin-wrappers:kotlin-react-redux"

    public const val kotlin_react_router_dom: String =
            "org.jetbrains.kotlin-wrappers:kotlin-react-router-dom"

    public const val kotlin_redux: String = "org.jetbrains.kotlin-wrappers:kotlin-redux"

    public const val kotlin_styled: String = "org.jetbrains.kotlin-wrappers:kotlin-styled"

    public const val kotlin_wrappers_bom: String =
            "org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom:_"

    public const val org_jetbrains_kotlin_plugin_serialization_gradle_plugin: String =
            "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin:_"

    public const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:_"

    public const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:_"

    public const val kotlin_serialization: String = "org.jetbrains.kotlin:kotlin-serialization:_"

    public const val kotlin_stdlib_common: String = "org.jetbrains.kotlin:kotlin-stdlib-common:_"

    public const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:_"

    public const val kotlin_stdlib_js: String = "org.jetbrains.kotlin:kotlin-stdlib-js:_"

    public const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test:_"

    public const val kotlin_test_annotations_common: String =
            "org.jetbrains.kotlin:kotlin-test-annotations-common:_"

    public const val kotlin_test_common: String = "org.jetbrains.kotlin:kotlin-test-common:_"

    public const val kotlin_test_js: String = "org.jetbrains.kotlin:kotlin-test-js:_"

    public const val kotlin_test_junit: String = "org.jetbrains.kotlin:kotlin-test-junit:_"

    public const val org_jetbrains_kotlinx_kover_gradle_plugin: String =
            "org.jetbrains.kotlinx.kover:org.jetbrains.kotlinx.kover.gradle.plugin:_"

    public const val kotlin_deeplearning_onnx: String =
            "org.jetbrains.kotlinx:kotlin-deeplearning-onnx:_"

    public const val kotlin_deeplearning_tensorflow: String =
            "org.jetbrains.kotlinx:kotlin-deeplearning-tensorflow:_"

    public const val kotlin_deeplearning_visualization: String =
            "org.jetbrains.kotlinx:kotlin-deeplearning-visualization:_"

    public const val kotlinx_cli: String = "org.jetbrains.kotlinx:kotlinx-cli:_"

    public const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"

    public const val kotlinx_coroutines_javafx: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-javafx:_"

    public const val kotlinx_coroutines_jdk8: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:_"

    public const val kotlinx_coroutines_test: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-test:_"

    public const val kotlinx_html: String = "org.jetbrains.kotlinx:kotlinx-html:_"

    public const val kotlinx_serialization_core: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-core:_"

    public const val kotlinx_serialization_json: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-json:_"

    public const val kotlinx_serialization_protobuf: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-protobuf:_"

    public const val fxgraphics2d: String = "org.jfree:fxgraphics2d:_"

    public const val jfxtras_all: String = "org.jfxtras:jfxtras-all:_"

    public const val jsoup: String = "org.jsoup:jsoup:_"

    public const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:_"

    public const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:_"

    public const val junit_jupiter_params: String = "org.junit.jupiter:junit-jupiter-params:_"

    public const val org_openjfx_javafxplugin_gradle_plugin: String =
            "org.openjfx.javafxplugin:org.openjfx.javafxplugin.gradle.plugin:_"

    public const val javafx_base: String = "org.openjfx:javafx-base:_"

    public const val javafx_controls: String = "org.openjfx:javafx-controls:_"

    public const val javafx_graphics: String = "org.openjfx:javafx-graphics:_"

    public const val opencv: String = "org.openpnp:opencv:_"

    public const val slf4j_api: String = "org.slf4j:slf4j-api:_"

    public const val org_springframework_boot_gradle_plugin: String =
            "org.springframework.boot:org.springframework.boot.gradle.plugin:_"

    public const val testfx_junit5: String = "org.testfx:testfx-junit5:_"

    public const val threeten_extra: String = "org.threeten:threeten-extra:_"

    public const val xmlunit: String = "xmlunit:xmlunit:_"
}
