/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/Splitties/refreshVersions
 */
object Libs {

  const val aopalliance: String = "aopalliance:aopalliance:_"

    const val aws_sdk_kotlin_s3: String = "aws.sdk.kotlin:s3:_"

    const val ca_cutterslade_analyze_gradle_plugin: String =
            "ca.cutterslade.analyze:ca.cutterslade.analyze.gradle.plugin:_"

    const val logback_classic: String = "ch.qos.logback:logback-classic:_"

    const val commonmark: String = "com.atlassian.commonmark:commonmark:_"

    const val commonmark_ext_gfm_tables: String =
            "com.atlassian.commonmark:commonmark-ext-gfm-tables:_"

    const val kaml: String = "com.charleskorn.kaml:kaml:_"

    const val com_cosminpolifronie_gradle_plantuml_gradle_plugin: String =
            "com.cosminpolifronie.gradle.plantuml:com.cosminpolifronie.gradle.plantuml.gradle.plugin:_"

    const val com_dorongold_task_tree_gradle_plugin: String =
            "com.dorongold.task-tree:com.dorongold.task-tree.gradle.plugin:_"

    const val jackson_databind: String = "com.fasterxml.jackson.core:jackson-databind:_"

    const val jackson_datatype_guava: String =
            "com.fasterxml.jackson.datatype:jackson-datatype-guava:_"

    const val jackson_datatype_jdk8: String =
            "com.fasterxml.jackson.datatype:jackson-datatype-jdk8:_"

    const val jackson_datatype_jsr310: String =
            "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:_"

    const val jackson_module_kotlin: String =
            "com.fasterxml.jackson.module:jackson-module-kotlin:_"

    const val jackson_module_parameter_names: String =
            "com.fasterxml.jackson.module:jackson-module-parameter-names:_"

    const val zjsonpatch: String = "com.flipkart.zjsonpatch:zjsonpatch:_"

    const val clikt: String = "com.github.ajalt.clikt:clikt:_"

    const val rxjava2_extras: String = "com.github.davidmoten:rxjava2-extras:_"

    const val docker_java: String = "com.github.docker-java:docker-java:_"

    const val docker_java_transport_httpclient5: String =
            "com.github.docker-java:docker-java-transport-httpclient5:_"

    const val kotlin_csv: String = "com.github.doyaaaaaken:kotlin-csv:_"

    const val kotlin_csv_js: String = "com.github.doyaaaaaken:kotlin-csv-js:_"

    const val kotlin_csv_jvm: String = "com.github.doyaaaaaken:kotlin-csv-jvm:_"

    const val com_github_hierynomus_license_base_gradle_plugin: String =
            "com.github.hierynomus.license-base:com.github.hierynomus.license-base.gradle.plugin:_"

    const val com_github_hierynomus_license_gradle_plugin: String =
            "com.github.hierynomus.license:com.github.hierynomus.license.gradle.plugin:_"

    const val image_comparison: String = "com.github.romankh3:image-comparison:_"

    const val rxkotlinfx: String = "com.github.thomasnield:rxkotlinfx:_"

    const val curvesapi: String = "com.github.virtuald:curvesapi:_"

    const val jsr305: String = "com.google.code.findbugs:jsr305:_"

    const val symbol_processing: String = "com.google.devtools.ksp:symbol-processing:_"

    const val symbol_processing_api: String =
            "com.google.devtools.ksp:symbol-processing-api:_"

    const val symbol_processing_cmdline: String =
            "com.google.devtools.ksp:symbol-processing-cmdline:_"

    const val guava: String = "com.google.guava:guava:_"

    const val guice_multibindings: String =
            "com.google.inject.extensions:guice-multibindings:_"

    const val guice: String = "com.google.inject:guice:_"

    const val annotations: String = "com.intellij:annotations:_"

    const val com_javagen_schema_gen_gradle_plugin: String =
            "com.javagen.schema-gen:com.javagen.schema-gen.gradle.plugin:_"

    const val jfoenix: String = "com.jfoenix:jfoenix:_"

    const val playwright: String = "com.microsoft.playwright:playwright:_"

    const val miglayout_javafx: String = "com.miglayout:miglayout-javafx:_"

    const val miglayout_swing: String = "com.miglayout:miglayout-swing:_"

    const val okhttp: String = "com.squareup.okhttp3:okhttp:_"

    const val javax_mail: String = "com.sun.mail:javax.mail:_"

    const val assertk: String = "com.willowtreeapps.assertk:assertk:_"

    const val commons_cli: String = "commons-cli:commons-cli:_"

    const val commons_codec: String = "commons-codec:commons-codec:_"

    const val commons_io: String = "commons-io:commons-io:_"

    const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    const val fontawesomefx: String = "de.jensd:fontawesomefx:_"

    const val de_undercouch_download_gradle_plugin: String =
            "de.undercouch.download:de.undercouch.download.gradle.plugin:_"

    const val edu_sc_seis_launch4j_gradle_plugin: String =
            "edu.sc.seis.launch4j:edu.sc.seis.launch4j.gradle.plugin:_"

    const val tilesfx: String = "eu.hansolo:tilesfx:_"

    const val vworkflows_fx: String = "eu.mihosoft.vrl.workflow:vworkflows-fx:_"

    const val io_codearte_nexus_staging_gradle_plugin: String =
            "io.codearte.nexus-staging:io.codearte.nexus-staging.gradle.plugin:_"

    const val flowext: String = "io.github.hoc081098:FlowExt:_"

    const val kohttp: String = "io.github.rybalkinsd:kohttp:_"

    const val ktor_swagger_ui: String = "io.github.smiley4:ktor-swagger-ui:_"

    const val detekt_gradle_plugin: String =
            "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:_"

    const val ktor_client_apache: String = "io.ktor:ktor-client-apache:_"

    const val ktor_client_auth: String = "io.ktor:ktor-client-auth:_"

    const val ktor_client_cio: String = "io.ktor:ktor-client-cio:_"

    const val ktor_client_content_negotiation: String =
            "io.ktor:ktor-client-content-negotiation:_"

    const val ktor_client_core: String = "io.ktor:ktor-client-core:_"

    const val ktor_client_encoding: String = "io.ktor:ktor-client-encoding:_"

    const val ktor_client_jetty: String = "io.ktor:ktor-client-jetty:_"

    const val ktor_client_json: String = "io.ktor:ktor-client-json:_"

    const val ktor_client_logging: String = "io.ktor:ktor-client-logging:_"

    const val ktor_client_mock: String = "io.ktor:ktor-client-mock:_"

    const val ktor_client_okhttp: String = "io.ktor:ktor-client-okhttp:_"

    const val ktor_client_serialization: String = "io.ktor:ktor-client-serialization:_"

    const val ktor_client_websockets: String = "io.ktor:ktor-client-websockets:_"

    const val ktor_http: String = "io.ktor:ktor-http:_"

    const val ktor_serialization_jackson: String = "io.ktor:ktor-serialization-jackson:_"

    const val ktor_serialization_kotlinx: String = "io.ktor:ktor-serialization-kotlinx:_"

    const val ktor_serialization_kotlinx_json: String =
            "io.ktor:ktor-serialization-kotlinx-json:_"

    const val ktor_server: String = "io.ktor:ktor-server:_"

    const val ktor_server_auth: String = "io.ktor:ktor-server-auth:_"

    const val ktor_server_auth_jwt: String = "io.ktor:ktor-server-auth-jwt:_"

    const val ktor_server_call_id: String = "io.ktor:ktor-server-call-id:_"

    const val ktor_server_conditional_headers: String =
            "io.ktor:ktor-server-conditional-headers:_"

    const val ktor_server_content_negotiation: String =
            "io.ktor:ktor-server-content-negotiation:_"

    const val ktor_server_core: String = "io.ktor:ktor-server-core:_"

    const val ktor_server_metrics: String = "io.ktor:ktor-server-metrics:_"

    const val ktor_server_netty: String = "io.ktor:ktor-server-netty:_"

    const val ktor_server_test_host: String = "io.ktor:ktor-server-test-host:_"

    const val ktor_server_websockets: String = "io.ktor:ktor-server-websockets:_"

    const val ktor_websocket_serialization: String = "io.ktor:ktor-websocket-serialization:_"

    const val ktor_websockets: String = "io.ktor:ktor-websockets:_"

    const val micrometer_registry_prometheus: String =
            "io.micrometer:micrometer-registry-prometheus:_"

    const val io_minio_minio: String = "io.minio:minio:_"

    const val mockk: String = "io.mockk:mockk:_"

    const val measured: String = "io.nacular.measured:measured:_"

    const val rxjava: String = "io.reactivex.rxjava2:rxjava:_"

    const val rxkotlin: String = "io.reactivex.rxjava2:rxkotlin:_"

    const val io_spring_dependency_management_gradle_plugin: String =
            "io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:_"

    const val javax_annotation_api: String = "javax.annotation:javax.annotation-api:_"

    const val javax_inject: String = "javax.inject:javax.inject:_"

    const val javax_mail_api: String = "javax.mail:javax.mail-api:_"

    const val mail: String = "javax.mail:mail:_"

    const val joda_time: String = "joda-time:joda-time:_"

    const val me_champeau_jmh_gradle_plugin: String =
            "me.champeau.jmh:me.champeau.jmh.gradle.plugin:_"

    const val mattermost_models: String = "net.bis5.mattermost4j:mattermost-models:_"

    const val mattermost4j_core: String = "net.bis5.mattermost4j:mattermost4j-core:_"

    const val image4j: String = "net.ifok.image:image4j:_"

    const val balloontip: String = "net.java.balloontip:balloontip:_"

    const val glazedlists_java16: String = "net.java.dev.glazedlists:glazedlists_java16:_"

    const val jna: String = "net.java.dev.jna:jna:_"

    const val svg2ico: String = "net.sourceforge.svg2ico:svg2ico:_"

    const val tornadofx: String = "no.tornado:tornadofx:_"

    const val commons_compress: String = "org.apache.commons:commons-compress:_"

    const val commons_lang3: String = "org.apache.commons:commons-lang3:_"

    const val commons_math3: String = "org.apache.commons:commons-math3:_"

    const val pdfbox: String = "org.apache.pdfbox:pdfbox:_"

    const val poi: String = "org.apache.poi:poi:_"

    const val poi_ooxml: String = "org.apache.poi:poi-ooxml:_"

    const val batik_svggen: String = "org.apache.xmlgraphics:batik-svggen:_"

    const val batik_svgrasterizer: String = "org.apache.xmlgraphics:batik-svgrasterizer:_"

    const val batik_swing: String = "org.apache.xmlgraphics:batik-swing:_"

    const val batik_transcoder: String = "org.apache.xmlgraphics:batik-transcoder:_"

    const val org_asciidoctor_jvm_convert_gradle_plugin: String =
            "org.asciidoctor.jvm.convert:org.asciidoctor.jvm.convert.gradle.plugin:_"

    const val org_asciidoctor_jvm_pdf_gradle_plugin: String =
            "org.asciidoctor.jvm.pdf:org.asciidoctor.jvm.pdf.gradle.plugin:_"

    const val awaitility: String = "org.awaitility:awaitility:_"

    const val org_barfuin_gradle_taskinfo_gradle_plugin: String =
            "org.barfuin.gradle.taskinfo:org.barfuin.gradle.taskinfo.gradle.plugin:_"

    const val bcprov_jdk15to18: String = "org.bouncycastle:bcprov-jdk15to18:_"

    const val staxmate: String = "org.codehaus.staxmate:staxmate:_"

    const val woodstox_core_asl: String = "org.codehaus.woodstox:woodstox-core-asl:_"

    const val controlsfx: String = "org.controlsfx:controlsfx:_"

    const val fest_reflect: String = "org.easytesting:fest-reflect:_"

    const val dictionary_reader: String = "org.eclipse.milo:dictionary-reader:_"

    const val sdk_client: String = "org.eclipse.milo:sdk-client:_"

    const val sdk_server: String = "org.eclipse.milo:sdk-server:_"

    const val freemarker: String = "org.freemarker:freemarker:_"

    const val fxyz3d: String = "org.fxyz3d:fxyz3d:_"

    const val gitlab4j_api: String = "org.gitlab4j:gitlab4j-api:_"

    const val chrome_devtools_kotlin: String = "org.hildan.chrome:chrome-devtools-kotlin:_"

    const val im4java: String = "org.im4java:im4java:_"

    const val all_modules_page_plugin: String =
            "org.jetbrains.dokka:all-modules-page-plugin:_"

    const val analysis_kotlin_descriptors: String =
            "org.jetbrains.dokka:analysis-kotlin-descriptors:_"

    const val dokka_base: String = "org.jetbrains.dokka:dokka-base:_"

    const val dokka_gradle_plugin: String = "org.jetbrains.dokka:dokka-gradle-plugin:_"

    const val gfm_plugin: String = "org.jetbrains.dokka:gfm-plugin:_"

    const val gfm_template_processing_plugin: String =
            "org.jetbrains.dokka:gfm-template-processing-plugin:_"

    const val javadoc_plugin: String = "org.jetbrains.dokka:javadoc-plugin:_"

    const val jekyll_plugin: String = "org.jetbrains.dokka:jekyll-plugin:_"

    const val jekyll_template_processing_plugin: String =
            "org.jetbrains.dokka:jekyll-template-processing-plugin:_"

    const val org_jetbrains_dokka_gradle_plugin: String =
            "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:_"

    const val org_jetbrains_intellij_gradle_plugin: String =
            "org.jetbrains.intellij:org.jetbrains.intellij.gradle.plugin:_"

    const val kotlin_css: String = "org.jetbrains.kotlin-wrappers:kotlin-css:_"

    const val kotlin_js: String = "org.jetbrains.kotlin-wrappers:kotlin-js:_"

    const val kotlin_react: String = "org.jetbrains.kotlin-wrappers:kotlin-react:_"

    const val kotlin_react_dom: String = "org.jetbrains.kotlin-wrappers:kotlin-react-dom:_"

    const val kotlin_react_router_dom: String =
            "org.jetbrains.kotlin-wrappers:kotlin-react-router-dom:_"

    const val kotlin_styled_next: String =
            "org.jetbrains.kotlin-wrappers:kotlin-styled-next:_"

    const val kotlin_wrappers_bom: String =
            "org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom:_"

    const val org_jetbrains_kotlin_plugin_serialization_gradle_plugin: String =
            "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin:_"

    const val kotlin_build_tools_impl: String =
            "org.jetbrains.kotlin:kotlin-build-tools-impl"

    const val kotlin_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-compiler-embeddable:_"

    const val kotlin_dom_api_compat: String = "org.jetbrains.kotlin:kotlin-dom-api-compat:_"

    const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:_"

    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:_"

    const val kotlin_serialization_compiler_plugin_embeddable: String =
            "org.jetbrains.kotlin:kotlin-serialization-compiler-plugin-embeddable:_"

    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    const val kotlin_stdlib_common: String = "org.jetbrains.kotlin:kotlin-stdlib-common:_"

    const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test:_"

    const val kotlin_test_annotations_common: String =
            "org.jetbrains.kotlin:kotlin-test-annotations-common:_"

    const val kotlin_test_common: String = "org.jetbrains.kotlin:kotlin-test-common:_"

    const val kotlin_test_js: String = "org.jetbrains.kotlin:kotlin-test-js:_"

    const val kotlin_test_junit5: String = "org.jetbrains.kotlin:kotlin-test-junit5:_"

    const val org_jetbrains_kotlinx_kover_gradle_plugin: String =
            "org.jetbrains.kotlinx.kover:org.jetbrains.kotlinx.kover.gradle.plugin:_"

    const val kotlinx_cli: String = "org.jetbrains.kotlinx:kotlinx-cli:_"

    const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"

    const val kotlinx_coroutines_debug: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-debug:_"

    const val kotlinx_coroutines_javafx: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-javafx:_"

    const val kotlinx_coroutines_jdk8: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:_"

    const val kotlinx_coroutines_jdk9: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-jdk9:_"

    const val kotlinx_coroutines_reactive: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-reactive:_"

    const val kotlinx_coroutines_test: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-test:_"

    const val kotlinx_datetime: String = "org.jetbrains.kotlinx:kotlinx-datetime:_"

    const val kotlinx_html: String = "org.jetbrains.kotlinx:kotlinx-html:_"

    const val kotlinx_serialization_core: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-core:_"

    const val kotlinx_serialization_json: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-json:_"

    const val kotlinx_serialization_protobuf: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-protobuf:_"

    const val kover_jvm_agent: String = "org.jetbrains.kotlinx:kover-jvm-agent:_"

    const val fxgraphics2d: String = "org.jfree:fxgraphics2d:_"

    const val jfxtras_all: String = "org.jfxtras:jfxtras-all:_"

    const val jsoup: String = "org.jsoup:jsoup:_"

    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:_"

    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:_"

    const val junit_jupiter_params: String = "org.junit.jupiter:junit-jupiter-params:_"

    const val bson_kotlinx: String = "org.mongodb:bson-kotlinx:_"

    const val mongodb_driver_kotlin_coroutine: String =
            "org.mongodb:mongodb-driver-kotlin-coroutine:_"

    const val jmh_core: String = "org.openjdk.jmh:jmh-core:_"

    const val jmh_generator_annprocess: String = "org.openjdk.jmh:jmh-generator-annprocess:_"

    const val jmh_generator_bytecode: String = "org.openjdk.jmh:jmh-generator-bytecode:_"

    const val org_openjfx_javafxplugin_gradle_plugin: String =
            "org.openjfx.javafxplugin:org.openjfx.javafxplugin.gradle.plugin:_"

    const val javafx_base: String = "org.openjfx:javafx-base:_"

    const val javafx_controls: String = "org.openjfx:javafx-controls:_"

    const val javafx_graphics: String = "org.openjfx:javafx-graphics:_"

    const val opencv: String = "org.openpnp:opencv:_"

    const val jsonassert: String = "org.skyscreamer:jsonassert:_"

    const val slf4j_api: String = "org.slf4j:slf4j-api:_"

    const val org_springframework_boot_gradle_plugin: String =
            "org.springframework.boot:org.springframework.boot.gradle.plugin:_"

    const val junit_jupiter: String = "org.testcontainers:junit-jupiter:_"

    const val org_testcontainers_minio: String = "org.testcontainers:minio:_"

    const val mongodb: String = "org.testcontainers:mongodb:_"

  const val chrome_testcontainers: String = "org.testcontainers:selenium:_"

    const val testcontainers: String = "org.testcontainers:testcontainers:_"

    const val testfx_junit5: String = "org.testfx:testfx-junit5:_"

    const val threeten_extra: String = "org.threeten:threeten-extra:_"

    const val swagger_ui: String = "org.webjars:swagger-ui:_"

    const val software_amazon_awssdk_s3: String = "software.amazon.awssdk:s3:_"

    const val xmlunit: String = "xmlunit:xmlunit:_"
}
