package it.neckar.gradle.pnpm.vite

import it.neckar.gradle.BuildInfoVars
import it.neckar.gradle.Plugins
import it.neckar.gradle.getBuildInfoVarValue
import org.gradle.api.DefaultTask
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.tasks.Delete
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.assign
import org.gradle.kotlin.dsl.create
import org.gradle.kotlin.dsl.named
import org.gradle.kotlin.dsl.register


/**
 * Generates a .env file with Git and build information for Vite projects.
 *
 * The .env file contains environment variables that Vite can use during build:
 * - VITE_GIT_COMMIT_DATE_TIME: Git commit date/time
 * - VITE_GIT_HASH: Full Git commit hash
 * - VITE_GIT_HASH_SHORT: Short Git commit hash
 * - VITE_BUILD_DATE: Build date (commit date, day only — reproducible)
 *
 * On local (non-CI, non-main) builds the git values are replaced with fixed placeholders
 * so the .env file does not change on every commit. VITE_BUILD_DATE stays the real commit
 * date (it changes at most once per commit day) — same gating as the HTML resource expansion.
 */
class GenerateViteEnvFilePlugin : Plugin<Project> {
  override fun apply(target: Project) {
    require(target != target.rootProject) {
      "GenerateViteEnvFilePlugin must not be applied to the root project"
    }

    target.plugins.apply(Plugins.base) //Ensure that the base plugin is applied

    val extension = target.extensions.create<GenerateViteEnvFilePluginExtension>(ExtensionName).apply {
      targetFile.convention(target.layout.projectDirectory.file(EnvFileName))
      viteVariables.convention(
        target.provider {
          //Uses getBuildInfoVarValue so local (non-CI, non-main) builds get the fixed
          //placeholders for the git values instead of per-commit values — keeps the
          //generated .env (and the downstream Vite build) cacheable, same as the HTML
          //resource expansion. BuildDate is the commit date (changes per commit day).
          mapOf(
            ViteVariableNames.GitCommitDateTime to target.getBuildInfoVarValue(BuildInfoVars.GitCommitDateTime),
            ViteVariableNames.GitHash to target.getBuildInfoVarValue(BuildInfoVars.GitHash),
            ViteVariableNames.GitHashShort to target.getBuildInfoVarValue(BuildInfoVars.GitHashShort),
            ViteVariableNames.BuildDate to target.getBuildInfoVarValue(BuildInfoVars.BuildDate),
          )
        }
      )
    }

    val generateEnvFileTask = target.tasks.register<GenerateViteEnvFileTask>(GenerateEnvFileTaskName) {
      group = "build"
      description = "Generates a .env file with Git and build information for Vite"

      targetFile = extension.targetFile
      viteVariables = extension.viteVariables
    }

    //Delete file on clean
    target.tasks.named<Delete>("clean") {
      delete(generateEnvFileTask.flatMap { it.targetFile })
    }
  }

  companion object {
    const val ExtensionName: String = "generateEnvFile"
    const val GenerateEnvFileTaskName: String = "generateEnvFile"

    private const val EnvFileName = ".env"
  }
}

/**
 * Vite environment variable names
 */
object ViteVariableNames {
  const val GitCommitDateTime: String = "VITE_GIT_COMMIT_DATE_TIME"
  const val GitHash: String = "VITE_GIT_HASH"
  const val GitHashShort: String = "VITE_GIT_HASH_SHORT"
  const val BuildDate: String = "VITE_BUILD_DATE"
}

interface GenerateViteEnvFilePluginExtension {
  /**
   * Where to write the generated .env file
   */
  val targetFile: RegularFileProperty

  /**
   * Map of Vite environment variables to generate
   */
  val viteVariables: MapProperty<String, String>
}

abstract class GenerateViteEnvFileTask : DefaultTask() {
  @get:OutputFile
  abstract val targetFile: RegularFileProperty

  @get:Input
  abstract val viteVariables: MapProperty<String, String>

  @TaskAction
  fun generate() {
    val targetFile = targetFile.get().asFile

    val content = buildString {
      appendLine("# Auto-generated Git and build information")
      appendLine("# DO NOT EDIT - This file is generated by Gradle")
      appendLine()

      viteVariables.get().forEach { (key, value) ->
        appendLine("""$key="$value"""")
      }
    }

    targetFile.writeText(content)

    project.logger.lifecycle("Generated ${targetFile.name} with Git and build information")
  }
}
