package it.neckar.gradle.pnpm.vite

import Plugins
import buildDate
import gitCommitDateTime
import gitHash
import gitHashShort
import org.gradle.api.DefaultTask
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.model.ObjectFactory
import org.gradle.api.provider.MapProperty
import org.gradle.api.tasks.Delete
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.assign
import org.gradle.kotlin.dsl.create
import org.gradle.kotlin.dsl.named
import org.gradle.kotlin.dsl.task


/**
 * Generates a .env file with Git and build information for Vite projects.
 *
 * The .env file contains environment variables that Vite can use during build:
 * - VITE_GIT_COMMIT_DATE_TIME: Git commit date/time
 * - VITE_GIT_HASH: Full Git commit hash
 * - VITE_GIT_HASH_SHORT: Short Git commit hash
 * - VITE_BUILD_DATE: Build date
 */
class GenerateViteEnvFilePlugin : Plugin<Project> {
  override fun apply(target: Project) {
    require(target != target.rootProject) {
      "GenerateViteEnvFilePlugin must not be applied to the root project"
    }

    target.plugins.apply(Plugins.base) //Ensure that the base plugin is applied

    val extension = target.extensions.create<GenerateViteEnvFilePluginExtension>("generateEnvFile", target).apply {
      targetFile.convention(target.layout.projectDirectory.file(EnvFileName))
    }

    val generateEnvFileTask = target.task<GenerateViteEnvFileTask>(GenerateEnvFileTaskName) {
      targetFile = extension.targetFile
      viteVariables = extension.viteVariables
    }

    //Delete file on clean
    target.tasks.named<Delete>("clean") {
      delete(generateEnvFileTask.targetFile)
    }
  }

  companion object {
    const val GenerateEnvFileTaskName: String = "generateEnvFile"

    private const val EnvFileName = ".env"
  }
}

/**
 * Vite environment variable names
 */
object ViteVariableNames {
  const val GitCommitDateTime: String = "VITE_GIT_COMMIT_DATE_TIME"
  const val GitHash: String = "VITE_GIT_HASH"
  const val GitHashShort: String = "VITE_GIT_HASH_SHORT"
  const val BuildDate: String = "VITE_BUILD_DATE"
}

open class GenerateViteEnvFilePluginExtension(
  objects: ObjectFactory,
  private val project: Project
) {
  /**
   * Where to write the generated .env file
   */
  val targetFile: RegularFileProperty = objects.fileProperty()

  /**
   * Map of Vite environment variables to generate
   */
  val viteVariables: MapProperty<String, String> = objects.mapProperty(String::class.java, String::class.java).convention(
    project.provider {
      mapOf(
        ViteVariableNames.GitCommitDateTime to project.gitCommitDateTime,
        ViteVariableNames.GitHash to project.gitHash,
        ViteVariableNames.GitHashShort to project.gitHashShort,
        ViteVariableNames.BuildDate to project.buildDate,
      )
    }
  )
}

open class GenerateViteEnvFileTask : DefaultTask() {
  init {
    group = "build"
    description = "Generates a .env file with Git and build information for Vite"
  }

  @OutputFile
  val targetFile: RegularFileProperty = project.objects.fileProperty()

  @Input
  val viteVariables: MapProperty<String, String> = project.objects.mapProperty(String::class.java, String::class.java)

  @TaskAction
  fun generate() {
    val targetFile = targetFile.get().asFile

    val content = buildString {
      appendLine("# Auto-generated Git and build information")
      appendLine("# DO NOT EDIT - This file is generated by Gradle")
      appendLine()

      viteVariables.get().forEach { (key, value) ->
        appendLine("""$key="$value"""")
      }
    }

    targetFile.writeText(content)

    project.logger.lifecycle("Generated ${targetFile.name} with Git and build information")
  }
}
