/*
 * Copyright (C) 2013-2026 Neckar IT GmbH, Mössingen, Germany
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Linking this library statically or dynamically with other modules is
 * making a combined work based on this library. Thus, the terms and
 * conditions of the GNU General Public License cover the whole combination.
 *
 * As a special exception, the copyright holders of this library give you
 * permission to link this library with independent modules, regardless of
 * the license terms of these independent modules, and to copy and distribute
 * the resulting combined work under terms of your choice, provided that every
 * copy of the combined work is accompanied by a complete copy of the source
 * code of this library.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package it.neckar.open.annotations

/**
 * The comment syntax of the format a generator writes. A format with none — JSON, binaries — gets
 * no marker.
 */
enum class GeneratedFileCommentSyntax(
  val linePrefix: String,

  /** Empty where the comment runs to the end of the line. */
  val lineSuffix: String,
) {
  /** Kotlin, TypeScript, JSON5. */
  DoubleSlash("//", ""),

  /** YAML, shell, Dockerfile fragments. */
  NumberSign("#", ""),

  /** HTML, SVG, XML. */
  XmlComment("<!--", " -->"),
}

/**
 * The marker of ADL 0180, for the first lines of a generated file:
 *
 *     // GENERATED by ts-declaration-generator — do not edit by hand.
 *     // Source: the Kotlin declarations annotated with @JsExport or @TsExport
 *     // Change the Kotlin declaration and rebuild.
 *
 * Without it an edit to a generated file survives until the next generator run and then disappears
 * without a message. Kotlin written into this build says the same through [Generated], which a test
 * can ask a loaded class for.
 *
 * Lives in the annotation root because that is the one module every other may depend on — the KSP
 * processors included, and those cannot depend on the libraries they process. Build Logic and the
 * spec generator have the same function again (`it.neckar.gradle.generated`, `spec_project.py`),
 * one per build boundary.
 *
 * @param by the generator, not the script inside it: two entry points writing one file must produce
 * the same bytes
 * @param source the input, repository-relative for a single file, a description for a set
 * @param regenerateHint what to do after changing the source; may span lines
 */
fun generatedFileMarker(
  by: String,
  source: String,
  regenerateHint: String,
  syntax: GeneratedFileCommentSyntax,
): String {
  require(by.isNotBlank()) { "generator name must not be blank" }
  require(source.isNotBlank()) { "source must not be blank — 'do not edit' is half an instruction, the other half is where the edit belongs" }
  require(regenerateHint.isNotBlank()) { "regenerate hint must not be blank" }

  return listOf(
    "GENERATED by $by — do not edit by hand.",
    "Source: $source",
    regenerateHint,
  )
    .flatMap { it.lines() }
    .joinToString(separator = "\n", postfix = "\n") { "${syntax.linePrefix} $it${syntax.lineSuffix}" }
}
